/**
 * Where the funding page comes from. Its single source is the skill asset
 * plugins/aztec-x402/skills/aztec-x402/assets/fund.html (also the file the
 * hosted copy serves). The CLI ships as its own npm package without the skill
 * folder, so `scripts/embed-fund-page.ts` writes the page into
 * page.generated.ts at build time; a unit test fails when the two drift.
 */
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const here = dirname(fileURLToPath(import.meta.url));
export const FUND_PAGE_SOURCE = join(here, "../../../../plugins/aztec-x402/skills/aztec-x402/assets/fund.html");
export const FUND_PAGE_MODULE = join(here, "page.generated.ts");

export function renderModule(html: string): string {
  return [
    "// Generated by scripts/embed-fund-page.ts from",
    "// plugins/aztec-x402/skills/aztec-x402/assets/fund.html. Do not edit.",
    `export const FUND_PAGE_HTML = ${JSON.stringify(html)};`,
    "",
  ].join("\n");
}
